#!/usr/bin/env bash

pushd () { command pushd "$@" > /dev/null ; }
popd () { command popd > /dev/null ; }

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd "$DIR"

cp -r `ls | sed '/^LICENSE$/d;/^README.md$/d;/^export_bin$/d'` ~/bin/

popd
